"""Items for Kirby: Squeak Squad. Scrolls and boss badges are progression."""
from typing import Dict, Tuple
from BaseClasses import Item, ItemClassification
ITEM_BASE_ID = 5_000_000
_IC = {"progression": ItemClassification.progression, "useful": ItemClassification.useful, "filler": ItemClassification.filler}
_ITEMS = [
    ('Star seal 1', 0, 'progression'),
    ('Star seal 2', 1, 'progression'),
    ('Star seal 3', 2, 'progression'),
    ('Star seal 4', 3, 'progression'),
    ('Star seal 5', 4, 'progression'),
    ('Sound player', 5, 'filler'),
    ('Vitality half_1', 6, 'useful'),
    ('Vitality half_2', 7, 'useful'),
    ('Orange', 8, 'filler'),
    ('Vitality half_4', 9, 'useful'),
    ('Vitality half_5', 10, 'useful'),
    ('Vitality half_6', 11, 'useful'),
    ('Vitality half_7', 12, 'useful'),
    ('Vitality half_8', 13, 'useful'),
    ('Prism Plains key', 14, 'progression'),
    ('Nature Notch key', 15, 'progression'),
    ('Cushy Cloud key', 16, 'progression'),
    ('Jam Jungle key', 17, 'progression'),
    ('Vocal Volcano key', 18, 'progression'),
    ('Ice Island key', 19, 'progression'),
    ('Secret Sea key', 20, 'progression'),
    ('Ghost medal_1', 21, 'filler'),
    ('Ghost medal_2', 22, 'filler'),
    ('Ghost medal_3', 23, 'filler'),
    ('Ghost medal_4', 24, 'filler'),
    ('Ghost medal_5', 25, 'filler'),
    ('Ghost medal_6', 26, 'filler'),
    ('Ghost medal_7', 27, 'filler'),
    ('Fire scroll', 28, 'progression'),
    ('Ice scroll', 29, 'progression'),
    ('Spark scroll', 30, 'progression'),
    ('Beam scroll', 31, 'progression'),
    ('Tornado scroll', 32, 'progression'),
    ('Enemy Sounds', 33, 'filler'),
    ('Hammer scroll', 34, 'progression'),
    ('Cupid scroll', 35, 'progression'),
    ('Cutter scroll', 36, 'progression'),
    ('Laser scroll', 37, 'progression'),
    ('Bomb scroll', 38, 'progression'),
    ('Wheel scroll', 39, 'progression'),
    ('HiJump scroll', 40, 'progression'),
    ('UFO scroll', 41, 'progression'),
    ('Copy palette 4', 42, 'filler'),
    ('Sword scroll', 43, 'progression'),
    ('Ninja scroll', 44, 'progression'),
    ('Fighter scroll', 45, 'progression'),
    ('Throw scroll', 46, 'progression'),
    ('Magic scroll', 47, 'progression'),
    ('Animal scroll', 48, 'progression'),
    ('Bubble scroll', 49, 'progression'),
    ('Metal scroll', 50, 'progression'),
    ('Party Notes', 51, 'filler'),
    ('Beginning Notes', 52, 'filler'),
    ('Happy Notes', 53, 'filler'),
    ('Graphic piece_17', 54, 'filler'),
    ('Battle Notes', 55, 'filler'),
    ('Familiar Notes', 56, 'filler'),
    ('Secret Notes', 57, 'filler'),
    ("Kirby's Sounds", 58, 'filler'),
    ('Parasol scroll', 59, 'progression'),
    ('Graphic piece_13', 60, 'filler'),
    ('Secret Sounds', 61, 'filler'),
    ('King DeDeDe badge', 62, 'progression'),
    ('Mrs Moley badge', 63, 'progression'),
    ('Mecha-Kracko badge', 64, 'progression'),
    ('Yadgaine badge', 65, 'progression'),
    ('Bohboh badge', 66, 'progression'),
    ('Daroach badge', 67, 'progression'),
    ('Meta Knight badge', 68, 'progression'),
    ('Dark Nebula badge', 69, 'filler'),
    ('Yellow', 70, 'filler'),
    ('Red', 71, 'filler'),
    ('Green', 72, 'filler'),
    ('Snow', 73, 'filler'),
    ('Carbon', 74, 'filler'),
    ('Ocean', 75, 'filler'),
    ('Sapphire', 76, 'filler'),
    ('Grape', 77, 'filler'),
    ('Emerald', 78, 'filler'),
    ('Graphic piece_8', 79, 'filler'),
    ('Chocolate', 80, 'filler'),
    ('Cherry', 81, 'filler'),
    ('Chalk', 82, 'filler'),
    ('Shadow', 83, 'filler'),
    ('Ivory', 84, 'filler'),
    ('Citrus', 85, 'filler'),
    ('White', 86, 'filler'),
    ('Lavender', 87, 'filler'),
    ('Copy palette 1', 88, 'filler'),
    ('Sleep scroll', 89, 'progression'),
    ('Copy palette 3', 90, 'filler'),
    ('Copy palette 5', 91, 'useful'),
    ('Copy palette 2', 92, 'filler'),
    ('Secret Map_1', 93, 'useful'),
    ('Secret Map_2', 94, 'useful'),
    ('Secret Map_3', 95, 'filler'),
    ('Secret Map_4', 96, 'useful'),
    ('Secret Map_5', 97, 'useful'),
    ('Secret Map_6', 98, 'useful'),
    ('Secret Map_7', 99, 'useful'),
    ('Graphic piece_1', 100, 'filler'),
    ('Spunky Notes', 101, 'useful'),
    ('Graphic piece_15', 102, 'filler'),
    ('Graphic piece_9', 103, 'filler'),
    ('Graphic piece_18', 104, 'filler'),
    ('Graphic piece_12', 105, 'filler'),
    ('Graphic piece_7', 106, 'filler'),
    ('Graphic piece_4', 107, 'filler'),
    ('Graphic piece_16', 108, 'filler'),
    ('Graphic piece_5', 109, 'filler'),
    ('Graphic piece_14', 110, 'filler'),
    ('Graphic piece_3', 111, 'filler'),
    ('Graphic piece_19', 112, 'filler'),
    ('Graphic piece_2', 113, 'filler'),
    ('Graphic piece_6', 114, 'filler'),
    ('Graphic piece_11', 115, 'filler'),
    ('Sound Effects', 116, 'filler'),
    ('Vitality half_3', 117, 'useful'),
    ('Graphic piece_10', 118, 'useful')
]
_FILLER = [
    ('Maxim Tomato', 200, 'filler', 8),
    ('Meat', 204, 'filler', 10),
    ('Energy Drink', 201, 'filler', 11),
    ('Cherries', 205, 'filler', 12),
    ('1-Up', 202, 'filler', 10)
]
ITEM_TABLE: Dict[str, Tuple] = {n:(_IC[c],1) for n,i,c in _ITEMS}
for n,off,c,q in _FILLER: ITEM_TABLE[n]=(_IC[c],q)
item_name_to_id: Dict[str,int] = {n: ITEM_BASE_ID+i for n,i,c in _ITEMS}
for n,off,c,q in _FILLER: item_name_to_id[n]=ITEM_BASE_ID+off
class KSSItem(Item):
    game = "Kirby Squeak Squad"
