"""Items for Kirby: Squeak Squad.
Boss badges, keys, star seals, and Progressive Ability items are progression.
Each copy ability is a Progressive item: x1 lets you USE the base ability
(enforced by the connector's ability watchdog); x2 sets that ability's scroll
bit in RAM, giving the upgraded scroll version.
"""
from typing import Dict, Tuple
from BaseClasses import Item, ItemClassification
ITEM_BASE_ID = 5_000_000
_IC = {"progression": ItemClassification.progression, "useful": ItemClassification.useful, "filler": ItemClassification.filler}
_ITEMS = [
    ('Star seal 1', 0, 'progression'),
    ('Star seal 2', 1, 'progression'),
    ('Star seal 3', 2, 'progression'),
    ('Star seal 4', 3, 'progression'),
    ('Star seal 5', 4, 'progression'),
    ('Sound player', 5, 'filler'),
    ('Vitality half_1', 6, 'useful'),
    ('Vitality half_2', 7, 'useful'),
    ('Orange', 8, 'filler'),
    ('Vitality half_4', 9, 'useful'),
    ('Vitality half_5', 10, 'useful'),
    ('Vitality half_6', 11, 'useful'),
    ('Vitality half_7', 12, 'useful'),
    ('Vitality half_8', 13, 'useful'),
    ('Prism Plains key', 14, 'progression'),
    ('Nature Notch key', 15, 'progression'),
    ('Cushy Cloud key', 16, 'progression'),
    ('Jam Jungle key', 17, 'progression'),
    ('Vocal Volcano key', 18, 'progression'),
    ('Ice Island key', 19, 'progression'),
    ('Secret Sea key', 20, 'progression'),
    ('Ghost medal_1', 21, 'filler'),
    ('Ghost medal_2', 22, 'filler'),
    ('Ghost medal_3', 23, 'filler'),
    ('Ghost medal_4', 24, 'filler'),
    ('Ghost medal_5', 25, 'filler'),
    ('Ghost medal_6', 26, 'filler'),
    ('Ghost medal_7', 27, 'filler'),
    ('Enemy Sounds', 33, 'filler'),
    ('Copy palette 4', 42, 'filler'),
    ('Party Notes', 51, 'filler'),
    ('Beginning Notes', 52, 'filler'),
    ('Happy Notes', 53, 'filler'),
    ('Graphic piece_17', 54, 'filler'),
    ('Battle Notes', 55, 'filler'),
    ('Familiar Notes', 56, 'filler'),
    ('Secret Notes', 57, 'filler'),
    ("Kirby's Sounds", 58, 'filler'),
    ('Graphic piece_13', 60, 'filler'),
    ('Secret Sounds', 61, 'filler'),
    ('King DeDeDe badge', 62, 'progression'),
    ('Mrs Moley badge', 63, 'progression'),
    ('Mecha-Kracko badge', 64, 'progression'),
    ('Yadgaine badge', 65, 'progression'),
    ('Bohboh badge', 66, 'progression'),
    ('Daroach badge', 67, 'progression'),
    ('Meta Knight badge', 68, 'progression'),
    ('Dark Nebula badge', 69, 'filler'),
    ('Yellow', 70, 'filler'),
    ('Red', 71, 'filler'),
    ('Green', 72, 'filler'),
    ('Snow', 73, 'filler'),
    ('Carbon', 74, 'filler'),
    ('Ocean', 75, 'filler'),
    ('Sapphire', 76, 'filler'),
    ('Grape', 77, 'filler'),
    ('Emerald', 78, 'filler'),
    ('Graphic piece_8', 79, 'filler'),
    ('Chocolate', 80, 'filler'),
    ('Cherry', 81, 'filler'),
    ('Chalk', 82, 'filler'),
    ('Shadow', 83, 'filler'),
    ('Ivory', 84, 'filler'),
    ('Citrus', 85, 'filler'),
    ('White', 86, 'filler'),
    ('Lavender', 87, 'filler'),
    ('Copy palette 1', 88, 'filler'),
    ('Copy palette 3', 90, 'filler'),
    ('Copy palette 5', 91, 'useful'),
    ('Copy palette 2', 92, 'filler'),
    ('Secret Map_1', 93, 'useful'),
    ('Secret Map_2', 94, 'useful'),
    ('Secret Map_3', 95, 'filler'),
    ('Secret Map_4', 96, 'useful'),
    ('Secret Map_5', 97, 'useful'),
    ('Secret Map_6', 98, 'useful'),
    ('Secret Map_7', 99, 'useful'),
    ('Graphic piece_1', 100, 'filler'),
    ('Spunky Notes', 101, 'useful'),
    ('Graphic piece_15', 102, 'filler'),
    ('Graphic piece_9', 103, 'filler'),
    ('Graphic piece_18', 104, 'filler'),
    ('Graphic piece_12', 105, 'filler'),
    ('Graphic piece_7', 106, 'filler'),
    ('Graphic piece_4', 107, 'filler'),
    ('Graphic piece_16', 108, 'filler'),
    ('Graphic piece_5', 109, 'filler'),
    ('Graphic piece_14', 110, 'filler'),
    ('Graphic piece_3', 111, 'filler'),
    ('Graphic piece_19', 112, 'filler'),
    ('Graphic piece_2', 113, 'filler'),
    ('Graphic piece_6', 114, 'filler'),
    ('Graphic piece_11', 115, 'filler'),
    ('Sound Effects', 116, 'filler'),
    ('Vitality half_3', 117, 'useful'),
    ('Graphic piece_10', 118, 'useful')
]
# Progressive copy-ability items (replace the old per-ability scroll items).
_PROGRESSIVE = [
    ('Progressive Fire', 500, 'progression'),
    ('Progressive Ice', 501, 'progression'),
    ('Progressive Spark', 502, 'progression'),
    ('Progressive Beam', 503, 'progression'),
    ('Progressive Tornado', 504, 'progression'),
    ('Progressive Hammer', 505, 'progression'),
    ('Progressive Cupid', 506, 'progression'),
    ('Progressive Cutter', 507, 'progression'),
    ('Progressive Laser', 508, 'progression'),
    ('Progressive Bomb', 509, 'progression'),
    ('Progressive Wheel', 510, 'progression'),
    ('Progressive HiJump', 511, 'progression'),
    ('Progressive UFO', 512, 'progression'),
    ('Progressive Sword', 513, 'progression'),
    ('Progressive Ninja', 514, 'progression'),
    ('Progressive Fighter', 515, 'progression'),
    ('Progressive Throw', 516, 'progression'),
    ('Progressive Magic', 517, 'progression'),
    ('Progressive Animal', 518, 'progression'),
    ('Progressive Bubble', 519, 'progression'),
    ('Progressive Metal', 520, 'progression'),
    ('Progressive Parasol', 521, 'progression'),
    ('Progressive Sleep', 522, 'progression')
]
_FILLER = [

    ('Maxim Tomato', 200, 'filler', 3),
    ('Meat', 204, 'filler', 4),
    ('Energy Drink', 201, 'filler', 4),
    ('Cherries', 205, 'filler', 4),
    ('1-Up', 202, 'filler', 4),
    ('Hamburger', 206, 'filler', 2),
    ('Nikuman', 207, 'filler', 2),
    ('Omelet', 208, 'filler', 2),
    ('Rice Ball', 209, 'filler', 2),
    ('Pudding', 210, 'filler', 2)
]
ITEM_TABLE: Dict[str, Tuple] = {n:(_IC[c],1) for n,i,c in _ITEMS}
for n,i,c in _PROGRESSIVE: ITEM_TABLE[n]=(_IC[c],2)          # two copies each
for n,off,c,q in _FILLER: ITEM_TABLE[n]=(_IC[c],q)
FILLER_NAMES = [n for n,off,c,q in _FILLER]
item_name_to_id: Dict[str,int] = {n: ITEM_BASE_ID+i for n,i,c in _ITEMS}
for n,i,c in _PROGRESSIVE: item_name_to_id[n]=ITEM_BASE_ID+i
for n,off,c,q in _FILLER: item_name_to_id[n]=ITEM_BASE_ID+off
class KSSItem(Item):
    game = "Kirby Squeak Squad"
