"""Items for Kirby: Squeak Squad.
Boss badges, keys, star seals, and Progressive Ability items are progression.
Each copy ability is a Progressive item: x1 lets you USE the base ability
(enforced by the connector's ability watchdog); x2 sets that ability's scroll
bit in RAM, giving the upgraded scroll version.
"""
from typing import Dict, Tuple
from BaseClasses import Item, ItemClassification
ITEM_BASE_ID = 5_000_000
_IC = {"progression": ItemClassification.progression, "useful": ItemClassification.useful, "filler": ItemClassification.filler}
_ITEMS = [
    ('Star Seal 1', 0, 'progression'),
    ('Star Seal 2', 1, 'progression'),
    ('Star Seal 3', 2, 'progression'),
    ('Star Seal 4', 3, 'progression'),
    ('Star Seal 5', 4, 'progression'),
    ('Sound Player', 5, 'filler'),
    ('Vitality Half 1', 6, 'useful'),
    ('Vitality Half 2', 7, 'useful'),
    ('Vitality Half 3', 8, 'useful'),
    ('Vitality Half 4', 9, 'useful'),
    ('Vitality Half 5', 10, 'useful'),
    ('Vitality Half 6', 11, 'useful'),
    ('Vitality Half 7', 12, 'useful'),
    ('Vitality Half 8', 13, 'useful'),
    ('Prism Plains Key', 14, 'progression'),
    ('Nature Notch Key', 15, 'progression'),
    ('Cushy Cloud Key', 16, 'progression'),
    ('Jam Jungle Key', 17, 'progression'),
    ('Vocal Volcano Key', 18, 'progression'),
    ('Ice Island Key', 19, 'progression'),
    ('Secret Sea Key', 20, 'progression'),
    ('Ghost Medal 1', 21, 'filler'),
    ('Ghost Medal 2', 22, 'filler'),
    ('Ghost Medal 3', 23, 'filler'),
    ('Ghost Medal 4', 24, 'filler'),
    ('Ghost Medal 5', 25, 'filler'),
    ('Ghost Medal 6', 26, 'filler'),
    ('Ghost Medal 7', 27, 'filler'),
    ('Enemy Sounds', 59, 'filler'),
    ('Animal Copy Palette', 89, 'filler'),
    ('Party Notes', 51, 'filler'),
    ('Beginning Notes', 52, 'filler'),
    ('Happy Notes', 53, 'filler'),
    ('Graphic Piece 17', 117, 'filler'),
    ('Battle Notes', 55, 'filler'),
    ('Familiar Notes', 56, 'filler'),
    ('Secret Notes', 57, 'filler'),
    ("Kirby's Sounds", 58, 'filler'),
    ('Graphic Piece 13', 116, 'filler'),
    ('Secret Sounds', 61, 'filler'),
    ('King DeDeDe Badge', 62, 'progression'),
    ('Mrs Moley Badge', 63, 'progression'),
    ('Mecha-Kracko Badge', 64, 'progression'),
    ('Yadgaine Badge', 65, 'progression'),
    ('Bohboh Badge', 66, 'progression'),
    ('Daroach Badge', 67, 'progression'),
    ('Meta Knight Badge', 68, 'progression'),
    ('Dark Nebula Badge', 69, 'filler'),
    ('Yellow', 70, 'filler'),
    ('Red', 71, 'filler'),
    ('Green', 72, 'filler'),
    ('Snow', 73, 'filler'),
    ('Carbon', 74, 'filler'),
    ('Ocean', 75, 'filler'),
    ('Sapphire', 76, 'filler'),
    ('Grape', 77, 'filler'),
    ('Emerald', 78, 'filler'),
    ('Graphic Piece 8', 101, 'filler'),
    ('Chocolate', 80, 'filler'),
    ('Cherry', 81, 'filler'),
    ('Chalk', 82, 'filler'),
    ('Shadow', 83, 'filler'),
    ('Ivory', 84, 'filler'),
    ('Citrus', 85, 'filler'),
    ('White', 86, 'filler'),
    ('Lavender', 87, 'filler'),
    ('Check Copy Palette', 88, 'filler'),
    ('Industrial Copy Palette', 90, 'filler'),
    ('Machine Copy Palette', 91, 'useful'),
    ('Pastel Copy Palette', 92, 'filler'),
    ('Secret Map 1', 93, 'useful'),
    ('Secret Map 2', 94, 'useful'),
    ('Secret Map 3', 95, 'filler'),
    ('Secret Map 4', 96, 'useful'),
    ('Secret Map 5', 97, 'useful'),
    ('Secret Map 6', 98, 'useful'),
    ('Secret Map 7', 99, 'useful'),
    ('Graphic Piece 1', 100, 'filler'),
    ('Spunky Notes', 54, 'useful'),
    ('Graphic Piece 15', 102, 'filler'),
    ('Graphic Piece 9', 103, 'filler'),
    ('Graphic Piece 18', 104, 'filler'),
    ('Graphic Piece 12', 105, 'filler'),
    ('Graphic Piece 7', 106, 'filler'),
    ('Graphic Piece 4', 107, 'filler'),
    ('Graphic Piece 16', 108, 'filler'),
    ('Graphic Piece 5', 109, 'filler'),
    ('Graphic Piece 14', 110, 'filler'),
    ('Graphic Piece 3', 111, 'filler'),
    ('Graphic Piece 19', 112, 'filler'),
    ('Graphic Piece 2', 113, 'filler'),
    ('Graphic Piece 6', 114, 'filler'),
    ('Graphic Piece 11', 115, 'filler'),
    ('Sound Effects', 60, 'filler'),
    ('Orange', 79, 'filler'),
    ('Graphic Piece 10', 118, 'useful')
]
# Progressive copy-ability items (replace the old per-ability scroll items).
_PROGRESSIVE = [
    ('Progressive Fire', 500, 'progression'),
    ('Progressive Ice', 501, 'progression'),
    ('Progressive Spark', 502, 'progression'),
    ('Progressive Beam', 503, 'progression'),
    ('Progressive Tornado', 504, 'progression'),
    ('Progressive Hammer', 505, 'progression'),
    ('Progressive Cupid', 506, 'progression'),
    ('Progressive Cutter', 507, 'progression'),
    ('Progressive Laser', 508, 'progression'),
    ('Progressive Bomb', 509, 'progression'),
    ('Progressive Wheel', 510, 'progression'),
    ('Progressive HiJump', 511, 'progression'),
    ('Progressive UFO', 512, 'progression'),
    ('Progressive Sword', 513, 'progression'),
    ('Progressive Ninja', 514, 'progression'),
    ('Progressive Fighter', 515, 'progression'),
    ('Progressive Throw', 516, 'progression'),
    ('Progressive Magic', 517, 'progression'),
    ('Progressive Animal', 518, 'progression'),
    ('Progressive Bubble', 519, 'progression'),
    ('Progressive Metal', 520, 'progression'),
    ('Progressive Parasol', 521, 'progression'),
    ('Progressive Sleep', 522, 'progression')
]
_FILLER = [

    ('Maxim Tomato', 200, 'filler', 3),
    ('Meat', 204, 'filler', 4),
    ('Energy Drink', 201, 'filler', 4),
    ('Cherries', 205, 'filler', 4),
    ('1-Up', 202, 'filler', 4),
    ('Hamburger', 206, 'filler', 2),
    ('Nikuman', 207, 'filler', 2),
    ('Omelet', 208, 'filler', 2),
    ('Rice Ball', 209, 'filler', 2),
    ('Pudding', 210, 'filler', 2)
]
ITEM_TABLE: Dict[str, Tuple] = {n:(_IC[c],1) for n,i,c in _ITEMS}
for n,i,c in _PROGRESSIVE: ITEM_TABLE[n]=(_IC[c],2)          # two copies each
for n,off,c,q in _FILLER: ITEM_TABLE[n]=(_IC[c],q)
FILLER_NAMES = [n for n,off,c,q in _FILLER]
item_name_to_id: Dict[str,int] = {n: ITEM_BASE_ID+i for n,i,c in _ITEMS}
for n,i,c in _PROGRESSIVE: item_name_to_id[n]=ITEM_BASE_ID+i
for n,off,c,q in _FILLER: item_name_to_id[n]=ITEM_BASE_ID+off
class KSSItem(Item):
    game = "Kirby Squeak Squad"
