"""Locations for Kirby: Squeak Squad.
Chest id = LOCATION_BASE_ID + bit_index ; stage-clear id = STAGECLEAR_BASE_ID + (10*world+sub)
"""
from typing import Dict
from BaseClasses import Location
LOCATION_BASE_ID = 5_000_100
STAGECLEAR_BASE_ID = 5_000_300
# (vanilla_name, bit_index, region, stage, required_powers)
_LOCS = [
    ('Star seal 1', 0, 'NatureNotch', '1', []),
    ('Star seal 2', 1, 'CushyCloud', '2', []),
    ('Star seal 3', 2, 'JamJungle', '2', []),
    ('Star seal 4', 3, 'VocalVolcano', '1', []),
    ('Star seal 5', 4, 'IceIsland', '2', []),
    ('Sound player', 5, 'PrismPlains', '3', []),
    ('Vitality half_1', 6, 'PrismPlainsEX', '6', []),
    ('Vitality half_2', 7, 'NatureNotchEX', '6', []),
    ('Orange', 8, 'CushyCloudEX', '6', ['Sword', 'Beam', 'UFO', 'Magic']),
    ('Vitality half_4', 9, 'JamJungle', '3', []),
    ('Vitality half_5', 10, 'VocalVolcano', '3', ['Metal']),
    ('Vitality half_6', 11, 'IceIsland', '3', []),
    ('Vitality half_7', 12, 'SecretSeaEX', '6', []),
    ('Vitality half_8', 13, 'GambleGalaxy', '3', []),
    ('Prism Plains key', 14, 'PrismPlains', '4', []),
    ('Nature Notch key', 15, 'NatureNotch', '5', []),
    ('Cushy Cloud key', 16, 'CushyCloud', '4', []),
    ('Jam Jungle key', 17, 'JamJungle', '4', ['Fire', 'Hammer']),
    ('Vocal Volcano key', 18, 'VocalVolcano', '4', []),
    ('Ice Island key', 19, 'IceIsland', '4', []),
    ('Secret Sea key', 20, 'SecretSea', '4', []),
    ('Ghost medal_1', 21, 'NatureNotch', '2', []),
    ('Ghost medal_2', 22, 'CushyCloud', '3', ['Bomb', 'Cutter', 'Laser', 'UFO']),
    ('Ghost medal_3', 23, 'JamJungleEX', '6', []),
    ('Ghost medal_4', 24, 'VocalVolcanoEX', '6', []),
    ('Ghost medal_5', 25, 'IceIslandEX', '6', []),
    ('Ghost medal_6', 26, 'SecretSea', '2', ['Fire', 'Hammer']),
    ('Ghost medal_7', 27, 'GambleGalaxy', '2', []),
    ('Fire scroll', 28, 'PrismPlains', '3', ['Animal']),
    ('Ice scroll', 29, 'JamJungleEX', '6', []),
    ('Spark scroll', 30, 'CushyCloud', '1', []),
    ('Beam scroll', 31, 'NatureNotch', '5', []),
    ('Tornado scroll', 32, 'CushyCloud', '5', []),
    ('Enemy Sounds', 33, 'VocalVolcano', '1', []),
    ('Hammer scroll', 34, 'VocalVolcano', '2', ['Beam', 'UFO']),
    ('Cupid scroll', 35, 'IceIsland', '5', []),
    ('Cutter scroll', 36, 'NatureNotch', '4', []),
    ('Laser scroll', 37, 'JamJungle', '5', []),
    ('Bomb scroll', 38, 'SecretSea', '3', []),
    ('Wheel scroll', 39, 'NatureNotch', '3', ['Fire', 'Wheel', 'Metal']),
    ('HiJump scroll', 40, 'CushyCloud', '4', []),
    ('UFO scroll', 41, 'GambleGalaxy', '1', []),
    ('Copy palette 4', 42, 'VocalVolcanoEX', '6', ['Metal', 'Hammer']),
    ('Sword scroll', 43, 'IceIsland', '1', []),
    ('Ninja scroll', 44, 'VocalVolcano', '3', ['Hammer', 'Fire', 'UFO', 'Throw']),
    ('Fighter scroll', 45, 'IceIsland', '3', ['Hammer', 'Metal']),
    ('Throw scroll', 46, 'SecretSea', '1', []),
    ('Magic scroll', 47, 'SecretSea', '4', []),
    ('Animal scroll', 48, 'NatureNotch', '1', []),
    ('Bubble scroll', 49, 'JamJungle', '1', []),
    ('Metal scroll', 50, 'JamJungle', '3', []),
    ('Party Notes', 51, 'JamJungleEX', '6', []),
    ('Beginning Notes', 52, 'PrismPlains', '2', []),
    ('Happy Notes', 53, 'IceIsland', '4', []),
    ('Graphic piece_17', 54, 'SecretSea', '3', ['Fire']),
    ('Battle Notes', 55, 'GambleGalaxy', '1', []),
    ('Familiar Notes', 56, 'CushyCloud', '2', []),
    ('Secret Notes', 57, 'GambleGalaxy', '3', ['UFO', 'Fire', 'Hammer']),
    ("Kirby's Sounds", 58, 'NatureNotch', '1', []),
    ('Parasol scroll', 59, 'VocalVolcano', '1', []),
    ('Graphic piece_13', 60, 'IceIsland', '1', []),
    ('Secret Sounds', 61, 'SecretSea', '1', []),
    ('King DeDeDe badge', 62, 'PrismPlains', '7', []),
    ('Mrs Moley badge', 63, 'NatureNotch', '7', []),
    ('Mecha-Kracko badge', 64, 'CushyCloud', '7', []),
    ('Yadgaine badge', 65, 'JamJungle', '7', []),
    ('Bohboh badge', 66, 'VocalVolcano', '7', []),
    ('Daroach badge', 67, 'IceIsland', '7', []),
    ('Meta Knight badge', 68, 'SecretSea', '7', []),
    ('Dark Nebula badge', 69, 'GambleGalaxy', '7', []),
    ('Yellow', 70, 'JamJungle', '2', []),
    ('Red', 71, 'VocalVolcano', '4', []),
    ('Green', 72, 'PrismPlains', '4', []),
    ('Snow', 73, 'IceIsland', '2', []),
    ('Carbon', 74, 'GambleGalaxy', '3', ['Animal']),
    ('Ocean', 75, 'SecretSea', '4', []),
    ('Sapphire', 76, 'SecretSea', '2', ['Fire']),
    ('Grape', 77, 'CushyCloud', '1', ['Hammer', 'Fire', 'UFO', 'Throw']),
    ('Emerald', 78, 'GambleGalaxy', '2', []),
    ('Graphic piece_8', 79, 'CushyCloudEX', '6', []),
    ('Chocolate', 80, 'SecretSea', '5', ['Wheel']),
    ('Cherry', 81, 'IceIslandEX', '6', ['Wheel']),
    ('Chalk', 82, 'IceIsland', '4', ['Cutter', 'Sword', 'Magic', 'Cupid', 'Ninja']),
    ('Shadow', 83, 'JamJungle', '1', ['HiJump', 'Laser']),
    ('Ivory', 84, 'VocalVolcano', '2', ['Fire', 'Ice', 'Beam', 'UFO']),
    ('Citrus', 85, 'NatureNotch', '2', []),
    ('White', 86, 'SecretSea', '1', []),
    ('Lavender', 87, 'CushyCloud', '4', ['Fire', 'Hammer']),
    ('Copy palette 1', 88, 'PrismPlains', '5', []),
    ('Sleep scroll', 89, 'VocalVolcanoEX', '6', []),
    ('Copy palette 3', 90, 'JamJungle', '3', []),
    ('Copy palette 5', 91, 'IceIsland', '5', []),
    ('Copy palette 2', 92, 'NatureNotch', '3', ['Bubble', 'Fire', 'Ice', 'UFO', 'Beam', 'Spark', 'Magic', 'Fighter', 'Bomb', 'Sword']),
    ('Secret Map_1', 93, 'NatureNotchEX', '6', []),
    ('Secret Map_2', 94, 'CushyCloud', '3', []),
    ('Secret Map_3', 95, 'JamJungle', '4', ['Fire', 'Hammer']),
    ('Secret Map_4', 96, 'VocalVolcano', '4', []),
    ('Secret Map_5', 97, 'IceIslandEX', '6', []),
    ('Secret Map_6', 98, 'SecretSeaEX', '6', []),
    ('Secret Map_7', 99, 'GambleGalaxy', '2', []),
    ('Graphic piece_1', 100, 'PrismPlains', '4', []),
    ('Spunky Notes', 101, 'SecretSea', '3', ['Fire', 'Beam', 'Bomb', 'Sword', 'UFO', 'Ice', 'Bubble', 'Magic']),
    ('Graphic piece_15', 102, 'IceIsland', '5', []),
    ('Graphic piece_9', 103, 'JamJungle', '1', ['Cutter', 'Bomb']),
    ('Graphic piece_18', 104, 'SecretSeaEX', '6', []),
    ('Graphic piece_12', 105, 'VocalVolcano', '3', ['Hammer', 'Metal']),
    ('Graphic piece_7', 106, 'CushyCloud', '3', []),
    ('Graphic piece_4', 107, 'NatureNotch', '5', ['Metal', 'Hammer', 'UFO', 'Fire', 'Throw']),
    ('Graphic piece_16', 108, 'SecretSea', '2', ['Fire']),
    ('Graphic piece_5', 109, 'NatureNotchEX', '6', ['Hammer', 'Metal']),
    ('Graphic piece_14', 110, 'IceIsland', '3', []),
    ('Graphic piece_3', 111, 'NatureNotch', '3', ['Animal']),
    ('Graphic piece_19', 112, 'GambleGalaxy', '1', ['Fire', 'Metal', 'Hammer']),
    ('Graphic piece_2', 113, 'PrismPlainsEX', '6', []),
    ('Graphic piece_6', 114, 'CushyCloud', '1', ['Bubble', 'Fire', 'UFO', 'Beam', 'Spark', 'Magic', 'Fighter', 'Bomb', 'Sword', 'Laser', 'Hammer']),
    ('Graphic piece_11', 115, 'VocalVolcano', '2', []),
    ('Sound Effects', 116, 'IceIsland', '1', ['Wheel', 'Animal']),
    ('Vitality half_3', 117, 'CushyCloudEX', '6', []),
    ('Graphic piece_10', 118, 'JamJungle', '4', [])
]
# (name, 10*world+sub, region)
_STAGECLEAR = [
    ('Prism Plains 2 Clear', 1, 'PrismPlains'),
    ('Prism Plains 3 Clear', 2, 'PrismPlains'),
    ('Prism Plains 4 Clear', 3, 'PrismPlains'),
    ('Prism Plains 5 Clear', 4, 'PrismPlains'),
    ('Prism Plains 6 Clear', 5, 'PrismPlainsEX'),
    ('Prism Plains 7 Clear', 6, 'PrismPlains'),
    ('Nature Notch 1 Clear', 10, 'NatureNotch'),
    ('Nature Notch 2 Clear', 11, 'NatureNotch'),
    ('Nature Notch 3 Clear', 12, 'NatureNotch'),
    ('Nature Notch 4 Clear', 13, 'NatureNotch'),
    ('Nature Notch 5 Clear', 14, 'NatureNotch'),
    ('Nature Notch 6 Clear', 15, 'NatureNotchEX'),
    ('Nature Notch 7 Clear', 16, 'NatureNotch'),
    ('Cushy Cloud 1 Clear', 20, 'CushyCloud'),
    ('Cushy Cloud 2 Clear', 21, 'CushyCloud'),
    ('Cushy Cloud 3 Clear', 22, 'CushyCloud'),
    ('Cushy Cloud 4 Clear', 23, 'CushyCloud'),
    ('Cushy Cloud 5 Clear', 24, 'CushyCloud'),
    ('Cushy Cloud 6 Clear', 25, 'CushyCloudEX'),
    ('Cushy Cloud 7 Clear', 26, 'CushyCloud'),
    ('Jam Jungle 1 Clear', 30, 'JamJungle'),
    ('Jam Jungle 2 Clear', 31, 'JamJungle'),
    ('Jam Jungle 3 Clear', 32, 'JamJungle'),
    ('Jam Jungle 4 Clear', 33, 'JamJungle'),
    ('Jam Jungle 5 Clear', 34, 'JamJungle'),
    ('Jam Jungle 6 Clear', 35, 'JamJungleEX'),
    ('Jam Jungle 7 Clear', 36, 'JamJungle'),
    ('Vocal Volcano 1 Clear', 40, 'VocalVolcano'),
    ('Vocal Volcano 2 Clear', 41, 'VocalVolcano'),
    ('Vocal Volcano 3 Clear', 42, 'VocalVolcano'),
    ('Vocal Volcano 4 Clear', 43, 'VocalVolcano'),
    ('Vocal Volcano 6 Clear', 45, 'VocalVolcanoEX'),
    ('Vocal Volcano 7 Clear', 46, 'VocalVolcano'),
    ('Ice Island 1 Clear', 50, 'IceIsland'),
    ('Ice Island 2 Clear', 51, 'IceIsland'),
    ('Ice Island 3 Clear', 52, 'IceIsland'),
    ('Ice Island 4 Clear', 53, 'IceIsland'),
    ('Ice Island 5 Clear', 54, 'IceIsland'),
    ('Ice Island 6 Clear', 55, 'IceIslandEX'),
    ('Ice Island 7 Clear', 56, 'IceIsland'),
    ('Secret Sea 1 Clear', 60, 'SecretSea'),
    ('Secret Sea 2 Clear', 61, 'SecretSea'),
    ('Secret Sea 3 Clear', 62, 'SecretSea'),
    ('Secret Sea 4 Clear', 63, 'SecretSea'),
    ('Secret Sea 5 Clear', 64, 'SecretSea'),
    ('Secret Sea 6 Clear', 65, 'SecretSeaEX'),
    ('Secret Sea 7 Clear', 66, 'SecretSea'),
    ('Gamble Galaxy 1 Clear', 70, 'GambleGalaxy'),
    ('Gamble Galaxy 2 Clear', 71, 'GambleGalaxy'),
    ('Gamble Galaxy 3 Clear', 72, 'GambleGalaxy'),
    ('Gamble Galaxy 7 Clear', 76, 'GambleGalaxy')
]
location_name_to_id: Dict[str,int] = {n: LOCATION_BASE_ID+i for n,i,r,s,p in _LOCS}
for n,key,region in _STAGECLEAR: location_name_to_id[n]=STAGECLEAR_BASE_ID+key
LOCATION_REGION: Dict[str,str] = {n:r for n,i,r,s,p in _LOCS}
for n,key,region in _STAGECLEAR: LOCATION_REGION[n]=region
LOCATION_POWERS: Dict[str,list] = {n:p for n,i,r,s,p in _LOCS}
ALL_LOCATIONS=[n for n,i,r,s,p in _LOCS]+[n for n,key,region in _STAGECLEAR]
VICTORY_EVENT="Strawberry Shortcake"
class KSSLocation(Location):
    game = "Kirby Squeak Squad"
